# Get this from https://data.gov.in/user/register

DATA_GOV_IN_API_KEY = "put your own api key"

# Get this from Google AI Studio (https://aistudio.google.com/app/apikey)

GOOGLE_API_KEY = "put your own api key"
