# Get this from https://data.gov.in/user/register

DATA_GOV_IN_API_KEY = "579b464db66ec23bdd000001bf2b2133beee43546cff2cf82e3e9aeb"

# Get this from Google AI Studio (https://aistudio.google.com/app/apikey)

GOOGLE_API_KEY = "AIzaSyB_LU1yLQF5u5LLWZFjzcDOfQitCyzXgzw"